services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${TAG:-5.1.4}
    container_name: ${CNTNR:-qbittorrent}
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT:-8080}:8080
      - ${TCP_PORT:-6881}:6881
      - ${UDP_PORT:-6881}:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-4096M}
    volumes:
      - ${ARR_DIR:-/home/administrator/}/qbittorrent/config:/config
      - ${MNT_DIR:-/home/administrator/downloads}/data/torrents:/data/torrents
