services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex-server
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} # Plex claim at https://account.plex.tv/claim
    devices:
      - "/dev/dri:dev/dri"
    volumes:
      - ${PLEX_DIR}/config:/config
    #  - /tmp/plex:/transcode
      - ${MNT_DIR}/PlexMedia/data/media/tv:/tv
      - ${MNT_DIR}/PlexMedia/data/media/movies:/movies
    restart: unless-stopped
