services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
   # network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Vienna
    volumes:
      - ${ARR_DIR}/flaresolverr/config:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
