services:
  nginx:
    image: nginx:${TAG:-1.27-alpine}
    container_name: ${CNTNR:-nginx}
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - ${NGINX_DIR}/build:/usr/share/nginx/html:ro
      - ${NGINX_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
