services:
   cloudflared:
      image: cloudflare/cloudflared:2025.10.1
      container_name: cloudflared
      restart: unless-stopped
      command: tunnel run
      environment:
       - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
      networks:
        - cloudflared
networks:
   cloudflared:
