services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:{TAG:-latest-fat}
    container_name: ${CNTNR:-stirling-pdf}
    ports:
      - '${HOST_PORT:-8080}:8080'
    volumes:
      - ${STIRLING_DIR}/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ${STIRLING_DIR}/extraConfigs:/configs
      - ${STIRLING_DIR}/customFiles:/customFiles/
      - ${STIRLING_DIR}/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - LANGS=en_GB
